<a href="https://colab.research.google.com/github/amaansadat/SRDT/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
a=np.array([1,2,3,4])

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arr[:,1]

array([2, 5, 8])

In [ ]:
arr[1,:]

array([4, 5, 6])

In [ ]:
arr[1: ,1: ]

array([[5, 6],
       [8, 9]])

In [ ]:
arr[(0,1,2),(0,1,2)]

array([1, 5, 9])

In [ ]:
arr[0: ,1: ] #print all the rows from index 0 too end AND colums from 1 to end.

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
my_list =[1,2,3]
my_list
my_list*2

[1, 2, 3, 1, 2, 3]

In [ ]:
np.array(my_list)*2

array([2, 4, 6])

In [ ]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.arange(1,20)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
np.arange(0,11,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3,3))*3

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [ ]:
#returns evenly spaced array
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
#eye()returns an identity matrix.

In [ ]:
#Rand() is used to create an array of given shape with random values
np.random.rand(3,2)

array([[0.7965239 , 0.8177793 ],
       [0.37770287, 0.7591213 ],
       [0.78962357, 0.9973412 ]])

In [ ]:
np.random.rand(2,2)*2


array([[1.47033292, 1.24811389],
       [1.87659713, 0.24472472]])

In [ ]:
#Reshape() is used to get the same array of same data with a new shape
arr = np.arange(49)
print(arr)
arr.reshape(1,49)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48]])

In [ ]:
#.max() is used to get max value of array.
#.argmax() returns the first appearance of max value.
#.min() is used to get min value of array.
#.argmin() returns the first appearance of min value.

In [ ]:
#Shape return the dimensions of array.
arr = np.arange(49)
print(arr)
print()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48]



In [ ]:
#Broadcasting is the process of auromatically expanding samller array to match the shape of larger array to perform operations.